// Critter Creamery flavor catalog. Shared by flavors.html and sundae-builder.html.
const FLAVOR_CATEGORIES = [
  {
    id: "favorites",
    name: "Favorites",
    image: "images/cat-favorites.png",
    blurb: "The flavors people line up for. Tried, true, and full of legs.",
    flavors: [
      { name: "Cricket Crunch Vanilla", bugs: "roasted crickets", desc: "Madagascar vanilla loaded with whole roasted crickets. Our best seller since day one." },
      { name: "Mealworm Fudge Ripple", bugs: "dried mealworms", desc: "Thick fudge ribbons and golden mealworms in every bite." },
      { name: "Grasshopper Mint Chip", bugs: "grasshoppers", desc: "Cool mint with whole grasshoppers where the chips would go. They snap like chocolate." },
      { name: "Honey Roasted Beetle Brittle", bugs: "darkling beetles", desc: "Caramel ice cream with shards of beetle brittle that shatter like toffee." },
      { name: "Strawberry Silkworm Swirl", bugs: "silkworm pupae", desc: "Fresh strawberry with a swirl of plump silkworms. Soft, sweet, and a little chewy." },
      { name: "Chocolate Covered Ant Fudge", bugs: "black ants", desc: "Dark chocolate speckled with thousands of ants. The crunch is somewhere between sprinkles and gravel." },
      { name: "Waxworm Caramel Crunch", bugs: "waxworms", desc: "Salted caramel studded with buttery waxworms. They taste like they were born for this." },
      { name: "Cicada Cookies and Cream", bugs: "cicadas", desc: "Crushed chocolate cookies, sweet cream, and whole cicadas, wings and all." },
      { name: "Centipede Chunk Rocky Road", bugs: "centipedes", desc: "Marshmallows, almonds, and curled centipedes in dark chocolate. Count the legs while you eat." },
      { name: "Hornet Honeycomb", bugs: "hornets", desc: "Wildflower honey ice cream with honeycomb pieces and the hornets that guarded them." },
      { name: "Earthworm Espresso", bugs: "earthworms", desc: "Double shot espresso ice cream with slow-roasted earthworms. Wakes you up twice." },
      { name: "Ladybug Lemon Chiffon", bugs: "ladybugs", desc: "Bright lemon with candied ladybugs. The polka dots are real." },
      { name: "Pill Bug Pistachio", bugs: "pill bugs", desc: "Roasted pistachio with pill bugs that curl into little armored gumballs." },
      { name: "Junebug Java Chip", bugs: "june beetles", desc: "Coffee ice cream with chocolate chips and june beetles picked at peak season." },
    ],
  },
  {
    id: "seasonal",
    name: "Seasonal",
    image: "images/cat-seasonal.png",
    blurb: "Bugs have seasons too. These rotate through the year, so catch them while they last.",
    flavors: [
      { name: "Pumpkin Spice Weevil", bugs: "grain weevils", desc: "Fall favorite. Pumpkin custard with cinnamon-dusted weevils." },
      { name: "Candy Cane Cricket", bugs: "crickets", desc: "Peppermint ice cream with crickets rolled in crushed candy cane." },
      { name: "Eggnog Earwig", bugs: "earwigs", desc: "Spiced eggnog with nutmeg-roasted earwigs. A holiday tradition at our counter." },
      { name: "Maple Bacon Bark Beetle", bugs: "bark beetles", desc: "Maple ice cream, candied bacon, and bark beetles straight from the log." },
      { name: "Peppermint Roach Ripple", bugs: "cockroaches", desc: "Winter only. Peppermint with a dark chocolate ripple and glossy candied roaches." },
      { name: "Gingerbread Termite", bugs: "termites", desc: "Gingerbread ice cream with termites who genuinely love the wood notes." },
      { name: "Springtime Aphid Honeydew", bugs: "aphids", desc: "Honeydew melon ice cream dusted with thousands of tiny green aphids." },
      { name: "May Beetle Melon", bugs: "may beetles", desc: "Cantaloupe sherbet with whole may beetles. Only here in May, obviously." },
      { name: "Firefly S'mores", bugs: "fireflies", desc: "Summer nights in a cone. Toasted marshmallow, graham, chocolate, and fireflies." },
      { name: "Watermelon Weevil Sorbet", bugs: "weevils", desc: "Dairy-free watermelon sorbet with black weevils standing in for the seeds." },
      { name: "Caramel Apple Inchworm", bugs: "inchworms", desc: "Apple pie ice cream with caramel and inchworms measuring every scoop." },
      { name: "Cider Cellar Special", bugs: "sowbugs and crickets", desc: "Mulled cider ice cream with the bugs we found near the cider barrels. Waste not." },
    ],
  },
  {
    id: "exotic",
    name: "Exotic",
    image: "images/cat-exotic.png",
    blurb: "Flavors and bugs from around the world. For the well-traveled tongue.",
    flavors: [
      { name: "Mango Bamboo Worm", bugs: "bamboo worms", desc: "Thai mango sticky rice ice cream with crispy bamboo worms." },
      { name: "Scorpion Prickly Pear", bugs: "scorpions", desc: "Desert pink prickly pear sorbet with a whole candied scorpion on top. Stinger included." },
      { name: "Tarantula Truffle", bugs: "tarantula", desc: "Black cocoa truffle ice cream with roasted tarantula leg pieces. Surprisingly nutty." },
      { name: "Dragon Fruit Dragonfly", bugs: "dragonflies", desc: "Hot pink dragon fruit with iridescent dragonfly wings folded through." },
      { name: "Wasabi Water Bug", bugs: "giant water bugs", desc: "A slow wasabi burn with giant water bugs that taste faintly of green apple. Really." },
      { name: "Lychee Locust", bugs: "locusts", desc: "Floral lychee ice cream with a plague-sized portion of roasted locusts." },
      { name: "Ube Rhino Beetle", bugs: "rhinoceros beetles", desc: "Purple yam ice cream with horn-on rhinoceros beetle halves." },
      { name: "Matcha Hornworm", bugs: "hornworms", desc: "Ceremonial grade matcha with bright green hornworms. They match. That's the point." },
      { name: "Tamarind Termite Swirl", bugs: "termites", desc: "Sweet and sour tamarind with a savory termite swirl." },
      { name: "Coconut Curry Cricket", bugs: "crickets", desc: "Coconut ice cream with yellow curry and turmeric-fried crickets." },
      { name: "Passionfruit Walking Stick", bugs: "stick insects", desc: "Tart passionfruit with whole walking sticks. Some customers use them as spoons." },
      { name: "Black Sesame Stink Bug", bugs: "stink bugs", desc: "Toasty black sesame with stink bugs that add a note of cilantro. Divisive. Beloved." },
    ],
  },
  {
    id: "deep-crawl",
    name: "The Deep Crawl",
    image: "images/cat-deep-crawl.png",
    blurb: "Our most intense flavors. Staff will ask if you are sure. Twice.",
    flavors: [
      { name: "Roach Road", bugs: "cockroaches", desc: "Dark chocolate with marshmallow and whole hissing cockroaches. The hiss stops in the churn." },
      { name: "Jerusalem Cricket Crumble", bugs: "Jerusalem crickets", desc: "Brown butter ice cream with oat crumble and Jerusalem crickets the size of your thumb." },
      { name: "Centipede Supreme", bugs: "giant centipedes", desc: "For centipede lovers who found Rocky Road too subtle. Triple the centipedes, zero apologies." },
      { name: "Night Crawler Neapolitan", bugs: "earthworms", desc: "Chocolate, vanilla, and strawberry, each stripe with its own earthworms." },
      { name: "Maggot Mascarpone", bugs: "fly larvae", desc: "Silky mascarpone gelato with clean-raised maggots. They wiggle less than you'd think." },
      { name: "Cockroach Cookie Dough", bugs: "cockroaches", desc: "Chunks of raw cookie dough, each one hiding a glossy brown roach." },
      { name: "Housefly Halva", bugs: "houseflies", desc: "Sesame halva ice cream with a generous cloud of crispy houseflies." },
      { name: "Slug and Snail Spumoni", bugs: "slugs and snails", desc: "Classic spumoni layers with garden slugs and snails, shells on." },
      { name: "Earwig Elderberry", bugs: "earwigs", desc: "Deep purple elderberry with earwigs tucked in every fold. Pincers add texture." },
      { name: "Grub Custard", bugs: "witchetty grubs", desc: "Rich frozen custard with whole roasted witchetty grubs. Creamy inside creamy." },
      { name: "Silverfish Sherbet", bugs: "silverfish", desc: "Pale citrus sherbet with quick little silverfish. Shimmery. Fast. Delicious." },
      { name: "Compost Heap Surprise", bugs: "roaches, worms, centipedes, and Jerusalem crickets", desc: "Coffee caramel base with everything from the bottom of the bin. The surprise is how good it is." },
      { name: "Leech Licorice", bugs: "leeches", desc: "Black licorice ice cream with chewy candied leeches. They hang on." },
      { name: "The Kitchen Sink", bugs: "every bug in the shop", desc: "One scoop, every single bug we carry. Finish it and your photo goes on the wall." },
    ],
  },
];
